### ISSUE TITLE
Firefox addon?

### ISSUE THREAD

**Issue by reallyuniquename** [shadyabhi/Reddit-New-Comments-Highlighter#1]
How do I use this on Firefox?

**Comment by shadyabhi** [comment]
I've added the build instructions to the README.md. However, the addon doesn't seem to be working. I'll make sure that it's fixed by this weekend.

**Comment by reallyuniquename** [comment]
Is there any way to use this as simple greasemonkey script?

**Comment by shadyabhi** [comment]
I'll check it out over the weekend. Give me 3 days of time. :) And yes, it can definitely be used as a greasemonkey script.

**Comment by reallyuniquename** [comment]
Any updates?

**Comment by shadyabhi** [comment]
@reallyuniquename So, I finally got time to fix this. The new code works again.

**Comment by shadyabhi** [comment]
Build instructions can be seen in readme.

**Comment by reallyuniquename** [comment]
Can you post built .xpi file or expain how use this as user-js?

**Comment by shadyabhi** [comment]
@reallyuniquename You can install it from here. https://addons.mozilla.org/en-US/firefox/addon/reddit-new-comments-highlighte/ . I just added it to Mozilla website, it'll take 3 days for review to complete.

**Comment by reallyuniquename** [comment]
It's still not available. Can't you just post .xpi or explain how to use this with greasemonkey?
